### ISSUE TITLE
`make examples` fails

### ISSUE THREAD

**Issue by vogler** [mirage/irmin#625] opened 2019-02-25 16:45 UTC
After `opam install irmin-unix` I can't build the examples. `opam install -t irmin-unix` also fails (cf. #624).
~~~
make examples
dune build @examples
File "examples/dune", line 3, characters 13-24:
3 |   (libraries checkseum.c digestif.c irmin irmin-unix))
                 ^^^^^^^^^^^
Error: Library "checkseum.c" not found.
Hint: try: dune external-lib-deps --missing @examples
make: *** [examples] Error 1
~~~
After `opam install checkseum digestif yaml graphql-lwt graphql-cohttp` it needs no more packages, but still fails:
~~~
make examples
dune build @examples
      ocamlc src/irmin-git/.irmin_git.objs/byte/irmin_git.{cmi,cmti} (exit 2)
(cd _build/default && /Users/voglerr/.opam/4.07.1+afl/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I src/irmin-git/.irmin_git.objs/byte -I /Users/voglerr/.opam/4.07.1+afl/lib/astring -I /Users/voglerr/.opam/4.07.1+afl/lib/bytes -I /Users/voglerr/.opam/4.07.1+afl/lib/cstruct -I /Users/voglerr/.opam/4.07.1+afl/lib/decompress -I /Users/voglerr/.opam/4.07.1+afl/lib/digestif -I /Users/voglerr/.opam/4.07.1+afl/lib/eqaf -I /Users/voglerr/.opam/4.07.1+afl/lib/fmt -I /Users/voglerr/.opam/4.07.1+afl/lib/git -I /Users/voglerr/.opam/4.07.1+afl/lib/hex -I /Users/voglerr/.opam/4.07.1+afl/lib/jsonm -I /Users/voglerr/.opam/4.07.1+afl/lib/logs -I /Users/voglerr/.opam/4.07.1+afl/lib/lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/mstruct -I /Users/voglerr/.opam/4.07.1+afl/lib/ocamlgraph -I /Users/voglerr/.opam/4.07.1+afl/lib/ocplib-endian -I /Users/voglerr/.opam/4.07.1+afl/lib/parsexp -I /Users/voglerr/.opam/4.07.1+afl/lib/re -I /Users/voglerr/.opam/4.07.1+afl/lib/re/posix -I /Users/voglerr/.opam/4.07.1+afl/lib/result -I /Users/voglerr/.opam/4.07.1+afl/lib/seq -I /Users/voglerr/.opam/4.07.1+afl/lib/sexplib -I /Users/voglerr/.opam/4.07.1+afl/lib/sexplib0 -I /Users/voglerr/.opam/4.07.1+afl/lib/stringext -I /Users/voglerr/.opam/4.07.1+afl/lib/uchar -I /Users/voglerr/.opam/4.07.1+afl/lib/uri -I /Users/voglerr/.opam/4.07.1+afl/lib/uutf -I src/irmin/.irmin.objs/byte -I src/irmin/.irmin.objs/native -no-alias-deps -opaque -o src/irmin-git/.irmin_git.objs/byte/irmin_git.cmi -c -intf src/irmin-git/irmin_git.mli)
File "src/irmin-git/irmin_git.mli", line 37, characters 20-28:
Error: Unbound module G.Hash
    ocamlopt src/irmin-graphql/.irmin_graphql.objs/native/irmin_graphql.{cmx,o} (exit 2)
(cd _build/default && /Users/voglerr/.opam/4.07.1+afl/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I src/irmin-graphql/.irmin_graphql.objs/byte -I src/irmin-graphql/.irmin_graphql.objs/native -I /Users/voglerr/.opam/4.07.1+afl/lib/astring -I /Users/voglerr/.opam/4.07.1+afl/lib/base -I /Users/voglerr/.opam/4.07.1+afl/lib/base/caml -I /Users/voglerr/.opam/4.07.1+afl/lib/base/shadow_stdlib -I /Users/voglerr/.opam/4.07.1+afl/lib/base64 -I /Users/voglerr/.opam/4.07.1+afl/lib/biniou -I /Users/voglerr/.opam/4.07.1+afl/lib/bytes -I /Users/voglerr/.opam/4.07.1+afl/lib/cohttp -I /Users/voglerr/.opam/4.07.1+afl/lib/cohttp-lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/digestif -I /Users/voglerr/.opam/4.07.1+afl/lib/easy-format -I /Users/voglerr/.opam/4.07.1+afl/lib/eqaf -I /Users/voglerr/.opam/4.07.1+afl/lib/fieldslib -I /Users/voglerr/.opam/4.07.1+afl/lib/fmt -I /Users/voglerr/.opam/4.07.1+afl/lib/graphql -I /Users/voglerr/.opam/4.07.1+afl/lib/graphql-cohttp -I /Users/voglerr/.opam/4.07.1+afl/lib/graphql-lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/graphql_parser -I /Users/voglerr/.opam/4.07.1+afl/lib/jsonm -I /Users/voglerr/.opam/4.07.1+afl/lib/logs -I /Users/voglerr/.opam/4.07.1+afl/lib/lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/ocamlgraph -I /Users/voglerr/.opam/4.07.1+afl/lib/ppx_sexp_conv/runtime-lib -I /Users/voglerr/.opam/4.07.1+afl/lib/re -I /Users/voglerr/.opam/4.07.1+afl/lib/re/posix -I /Users/voglerr/.opam/4.07.1+afl/lib/result -I /Users/voglerr/.opam/4.07.1+afl/lib/rresult -I /Users/voglerr/.opam/4.07.1+afl/lib/seq -I /Users/voglerr/.opam/4.07.1+afl/lib/sexplib0 -I /Users/voglerr/.opam/4.07.1+afl/lib/stringext -I /Users/voglerr/.opam/4.07.1+afl/lib/uchar -I /Users/voglerr/.opam/4.07.1+afl/lib/uri -I /Users/voglerr/.opam/4.07.1+afl/lib/uri/sexp -I /Users/voglerr/.opam/4.07.1+afl/lib/uutf -I /Users/voglerr/.opam/4.07.1+afl/lib/yojson -I src/irmin/.irmin.objs/byte -I src/irmin/.irmin.objs/native -intf-suffix .ml -no-alias-deps -opaque -o src/irmin-graphql/.irmin_graphql.objs/native/irmin_graphql.cmx -c -impl src/irmin-graphql/irmin_graphql.ml)
File "src/irmin-graphql/irmin_graphql.ml", line 42, characters 54-56:
Error: Signature mismatch:
       ...
       The value `of_string' is required but not provided
       File "graphql-cohttp/src/graphql_cohttp.mli", line 6, characters 2-29:
         Expected declaration
       The value `to_string' is required but not provided
       File "graphql-cohttp/src/graphql_cohttp.mli", line 5, characters 2-32:
         Expected declaration
    ocamlopt src/irmin-http/.irmin_http.objs/native/irmin_http_server.{cmx,o} (exit 2)
(cd _build/default && /Users/voglerr/.opam/4.07.1+afl/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I src/irmin-http/.irmin_http.objs/byte -I src/irmin-http/.irmin_http.objs/native -I /Users/voglerr/.opam/4.07.1+afl/lib/astring -I /Users/voglerr/.opam/4.07.1+afl/lib/base -I /Users/voglerr/.opam/4.07.1+afl/lib/base/caml -I /Users/voglerr/.opam/4.07.1+afl/lib/base/shadow_stdlib -I /Users/voglerr/.opam/4.07.1+afl/lib/base64 -I /Users/voglerr/.opam/4.07.1+afl/lib/bytes -I /Users/voglerr/.opam/4.07.1+afl/lib/calendar -I /Users/voglerr/.opam/4.07.1+afl/lib/cohttp -I /Users/voglerr/.opam/4.07.1+afl/lib/cohttp-lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/digestif -I /Users/voglerr/.opam/4.07.1+afl/lib/dispatch -I /Users/voglerr/.opam/4.07.1+afl/lib/eqaf -I /Users/voglerr/.opam/4.07.1+afl/lib/fieldslib -I /Users/voglerr/.opam/4.07.1+afl/lib/fmt -I /Users/voglerr/.opam/4.07.1+afl/lib/jsonm -I /Users/voglerr/.opam/4.07.1+afl/lib/logs -I /Users/voglerr/.opam/4.07.1+afl/lib/lwt -I /Users/voglerr/.opam/4.07.1+afl/lib/ocamlgraph -I /Users/voglerr/.opam/4.07.1+afl/lib/ppx_sexp_conv/runtime-lib -I /Users/voglerr/.opam/4.07.1+afl/lib/re -I /Users/voglerr/.opam/4.07.1+afl/lib/re/posix -I /Users/voglerr/.opam/4.07.1+afl/lib/re/str -I /Users/voglerr/.opam/4.07.1+afl/lib/result -I /Users/voglerr/.opam/4.07.1+afl/lib/seq -I /Users/voglerr/.opam/4.07.1+afl/lib/sexplib0 -I /Users/voglerr/.opam/4.07.1+afl/lib/stringext -I /Users/voglerr/.opam/4.07.1+afl/lib/uchar -I /Users/voglerr/.opam/4.07.1+afl/lib/uri -I /Users/voglerr/.opam/4.07.1+afl/lib/uri/sexp -I /Users/voglerr/.opam/4.07.1+afl/lib/uutf -I /Users/voglerr/.opam/4.07.1+afl/lib/webmachine -I src/irmin/.irmin.objs/byte -I src/irmin/.irmin.objs/native -intf-suffix .ml -no-alias-deps -opaque -o src/irmin-http/.irmin_http.objs/native/irmin_http_server.cmx -c -impl src/irmin-http/irmin_http_server.ml)
File "src/irmin-http/irmin_http_server.ml", line 41, characters 12-36:
Error: This module is not a functor; it has type
       sig
         type 'a io = 'a Lwt.t
         type 'a result =
           'a Webmachine.Make(HTTP.IO).result =
             Ok of 'a
           | Error of int
         type ('a, 'b) op = 'b Rd.t -> ('a result * 'b Rd.t) io
           constraint 'b = [> `Empty ]
         type 'a provider = ('a, 'a) op constraint 'a = [> `Empty ]
         type 'a acceptor = (bool, 'a) op constraint 'a = [> `Empty ]
         type www_authenticate =
           Webmachine.Make(HTTP.IO).www_authenticate = {
           scheme : string;
           realm : string;
           params : (string * string) list;
         }
         type auth =
             [ `Authorized
             | `Basic of string
             | `Challenge of www_authenticate
             | `Redirect of Uri.t ]
         val continue : 'a -> ('a, [> `Empty ]) op
         val respond : ?body:([> `Empty ] as 'b) -> int -> ('a, 'b) op
         class virtual ['a] resource :
           object
             constraint 'a = [> `Empty ]
             method allowed_methods : (Cohttp.Code.meth list, 'a) op
             method charsets_provided : ((string * ('a -> 'a)) list, 'a) op
             method virtual content_types_accepted :
               ((string * 'a acceptor) list, 'a) op
             method virtual content_types_provided :
               ((string * 'a provider) list, 'a) op
             method delete_completed : (bool, 'a) op
             method delete_resource : (bool, 'a) op
             method encodings_provided : ((string * ('a -> 'a)) list, 'a) op
             method expires : (string option, 'a) op
             method finish_request : (unit, 'a) op
             method forbidden : (bool, 'a) op
             method generate_etag : (string option, 'a) op
             method is_authorized : (auth, 'a) op
             method is_conflict : (bool, 'a) op
             method known_content_type : (bool, 'a) op
             method known_methods : (Cohttp.Code.meth list, 'a) op
             method language_available : (bool, 'a) op
             method last_modified : (string option, 'a) op
             method malformed_request : (bool, 'a) op
             method moved_permanently : (Uri.t option, 'a) op
             method moved_temporarily : (Uri.t option, 'a) op
             method multiple_choices : (bool, 'a) op
             method options : ((string * string) list, 'a) op
             method previously_existed : (bool, 'a) op
             method process_post : (bool, 'a) op
             method resource_exists : (bool, 'a) op
             method service_available : (bool, 'a) op
             method uri_too_long : (bool, 'a) op
             method valid_content_headers : (bool, 'a) op
             method valid_entity_length : (bool, 'a) op
             method variances : (string list, 'a) op
           end
         val to_handler :
           ?dispatch_path:string ->
           ?path_info:(string * string) list ->
           resource:([> `Empty ] as 'a) resource ->
           body:'a ->
           request:Cohttp.Request.t ->
           unit ->
           (Cohttp.Code.status_code * Cohttp.Header.t * 'a * string list) io
         val dispatch :
           ((Dispatch.tag * string) list * Dispatch.typ *
            (unit -> ([> `Empty ] as 'a) resource))
           list ->
           body:'a ->
           request:Cohttp.Request.t ->
           (Cohttp.Code.status_code * Cohttp.Header.t * 'a * string list)
           option io
         val dispatch' :
           (string * (unit -> ([> `Empty ] as 'a) resource)) list ->
           body:'a ->
           request:Cohttp.Request.t ->
           (Cohttp.Code.status_code * Cohttp.Header.t * 'a * string list)
           option io
       end
make: *** [examples] Error 1
~~~

**Comment by samoht** [comment] 2019-03-07 16:50
Which version of cohttp do you have ? I cannot reproduce your issue.

**Comment by vogler** [comment] 2019-03-08 15:26
`cohttp.2.0.0`

It's a problem with the version in opam-repository since everything works when installed via `opam install .`.

Just noticed that not just the examples don't build:
~~~
make
dune build
File "src/irmin-graphql/dune", line 4, characters 13-24:
4 |   (libraries graphql-lwt graphql-cohttp cohttp-lwt irmin))
                 ^^^^^^^^^^^
Error: Library "graphql-lwt" not found.
Hint: try: dune external-lib-deps --missing @@default
File "src/irmin-mirage/dune", line 4, characters 54-64:
4 |  (libraries   irmin irmin-mem irmin-git irmin-graphql git-mirage ptime
                                                          ^^^^^^^^^^
Error: Library "git-mirage" not found.
Hint: try: dune external-lib-deps --missing @@default
File "src/irmin-test/dune", line 4, characters 42-50:
4 |   (libraries   irmin mtime mtime.clock.os alcotest lwt.unix logs.fmt))
                                              ^^^^^^^^
Error: Library "alcotest" not found.
Hint: try: dune external-lib-deps --missing @@default
File "src/irmin-unix/dune", line 5, characters 28-32:
5 |               irmin-watcher yaml cmdliner logs.fmt logs.cli fmt.cli fmt.tty))
                                ^^^^
Error: Library "yaml" not found.
Hint: try: dune external-lib-deps --missing @@default
File "src/irmin/dune", line 4, characters 56-64:
4 |  (libraries   fmt uri jsonm lwt ocamlgraph logs astring digestif))
                                                            ^^^^^^^^
Error: Library "digestif" not found.
Hint: try: dune external-lib-deps --missing @@default
File "src/irmin-unix/bin/dune", line 5, characters 15-26:
5 |   (libraries   checkseum.c digestif.c irmin-unix))
                   ^^^^^^^^^^^
Error: Library "checkseum.c" not found.
Hint: try: dune external-lib-deps --missing @@default
make: *** [all] Error 1
~~~

**Comment by samoht** [comment] 2019-03-08 17:22
Did you try to `opam update && opam install .` first?

**Comment by vogler** [comment] 2019-03-08 19:37
I did `opam update` and `opam install .` works, however, `opam install irmin-unix` does not. So, I guess there's something wrong with the `opam` file in `opam-repository` which has been fixed by now in this repo.

**Comment by samoht** [comment] 2019-04-08 21:18
Cannot reproduce on master, so closing.

**Closed by samoht** 2019-04-08 21:18 UTC

**Comment by aweis** [comment] 2019-04-24 07:13
i think I am seeing the same issue
