### ISSUE TITLE
Error loading irmin.mirage from utop.

### ISSUE THREAD

**Issue by mmaker** [mirage/irmin#338] opened 2016-03-12 18:41 UTC
On a fresh utop session:

```
utop # #require "irmin.mirage";;
Error: The external function `caml_alloc_pages' is not available 
```

Can be fixed loading `io-page.unix` first (credits to @yomimono): 

```
utop # #require "io-page.unix";;
utop # #require "irmin.mirage";;
```

**Comment by samoht** [comment] 2016-03-12 18:55
Hum loading `io-page.uni` on unix doesn't feel right ... I'm wondering where the missing dependency comes from.

**Comment by samoht** [comment] 2019-05-07 12:02
New error with irmin 2.0:

```
$ dune utop
File "_none_", line 1:
Error: Required module `Checkseum' is unavailable
```

/cc @dinosaure

**Comment by dinosaure** [comment] 2019-05-07 12:50
This kind of bug can not be fixed now mostly because the inability of `dune` to choose a default implementation. A PR was made by @TheLortex (mirage/checkseum#25) and with this branch, `dune utop` raises an other (and expected) error about `digestif` which follows the same pattern. However, [due to the state](https://discuss.ocaml.org/t/dune-serious-bug-found-in-the-design-of-library-variants/3743/4) of variants, I don't have a recent plan to fix it.

**Comment by dinosaure** [comment] 2019-05-25 11:11
Release of `checkseum.0.1.0` and `digestif.0.7.2` fix the second problem but we still have:

```sh
utop # #require "irmin.mirage";;
Error: The external function `caml_alloc_pages' is not available 
```

**Comment by hannesm** [comment] 2019-05-26 10:25
`caml_alloc_pages` originates from `io-page` before 2.0.0 (it got renamed to `mirage_alloc_pages` in https://github.com/mirage/io-page/commit/9ed4cfd831f2436e99ec07ed7bad74ef91ac06f6). which library depends on io-page in your dependency cone (from my intuition there shouldn't be any)? and why do they depend on an arcane io-page version?

**Comment by pascutto** [comment] 2019-09-20 08:21
I tried to reproduce the `caml_alloc_pages` issue but wasn't able to.
 
- On a fresh switch, installing `irmin-*` installs `io-page.2.3.0`, which suggests that the issue raised by @hannesm has been solved somewhere?
- I do get the missing `digestif` implementation error however. Is there anything we can do (now or in the future) in `irmin` or will this ultimately be fixed in `digestif` @dinosaure? Just trying to figure out what the status of this issue is, and if it should live in another repo instead.

**Comment by dinosaure** [comment] 2019-09-20 08:30
About digestif, a fresh switch should install digestif.0.7.4 which is a compat' version for Mirage 3 and it does not integrate dune's variants. To fix it, you should add a conflict with this specific version. digestif.0.7.3 should work perfectly.

**Comment by samoht** [comment] 2019-09-20 08:31
This should be fixed by dune's [default implementation of virtual libraries](https://dune.readthedocs.io/en/stable/variants.html#default-implementation) which, AFAIK is not used by `digestif` yet. I've opened https://github.com/mirage/digestif/issues/90 to track this.

**Comment by samoht** [comment] 2019-09-20 08:32
@dinosaure that's not very nice to add such a regression in a minor release :-(

**Comment by dinosaure** [comment] 2019-09-20 08:47
> @dinosaure that's not very nice to add such a regression in a minor release :-(

This is not a regression where, as I said, digestif.0.7.4 is a special version and diverge from `master`. Furthermore, future versions of digestif will based on digestif.0.7.3 (as current master of digestif is based on digestif.0.7.3).

I would like have a custom release like `digestif.0.7.3+mirage3` or something like this to avoid any trouble but after some discussions, this way, even if we need to put a conflict, seems the best.

Then, the only diff between digestif.0.7.3 and digestif.0.7.4 is the way to build.

**Comment by pascutto** [comment] 2019-09-20 08:57
Using `0.7.3` indeed fixes the `digestif` issue.

Regarding `caml_alloc_pages` (now `mirage_alloc_pages`), this has been reported in https://github.com/mirage/io-page/issues/50, and probably fixed by https://github.com/mirage/io-page/pull/60 if I understand correctly.
So I guess we have to wait for the next `io-page` release to fix this.

**Comment by samoht** [comment] 2019-09-20 09:00
yes it's a regression: it will break the build of people using `digestif 0.7.3` are upgrading to `digestif 0.7.4`. It happened to tezos a few days ago and people were confused about the error. I understand the rational, but this is just very confusing. Using `digestif.0.7.3~mirage3` would probably have been better.

**Comment by hannesm** [comment] 2019-09-20 09:29
uh, that's not very nice. I asked @dinosaure to do a release which is usable with mirage3 back then, so I can actually use irmin+git with mirageos. the constraints are conflicts with mirage-runtime (< > 4.0.0), but that's of course not relevant for e.g. tezos -- i.e. projects which do not depend on mirage.

now, a good solution would be to support both mirage3 and mirage4 in a digestif/checkseum release; since this seems to not easily work, I guess it'd be fine to release a variants-based digestif 0.8.0 (basically the same as 0.7.3, needs to conflict with mirage-runtime < 4) -- so people who don't care about mirageos will get that now, and uses of mirage will get the 0.7.4 for "cross"-compilation.

**Comment by dinosaure** [comment] 2019-09-20 09:47
> Using digestif.0.7.3~mirage3 would probably have been better.

I asked to @kit-ty-kate and she advises me to do not do that.

> now, a good solution would be to support both mirage3 and mirage4 in a digestif/checkseum release; since this seems to not easily work, I guess it'd be fine to release a variants-based digestif 0.8.0 

If people are happy with this solution, I can make a new release as I said in https://github.com/mirage/digestif/issues/90#issuecomment-533470857.

**Comment by kit-ty-kate** [comment] 2019-09-20 12:01
> > Using digestif.0.7.3~mirage3 would probably have been better.
> 
> I asked to @kit-ty-kate and she advises me to do not do that.

I don't recall that. Do you remember where that was? I remember merging the PR but there wasn't really much clues about its nature: https://github.com/ocaml/opam-repository/pull/14730

**Comment by pascutto** [comment] 2019-09-20 12:14
It's probably better to track and solve the digestif versioning issue in https://github.com/mirage/digestif/issues/90, so we can focus on the `irmin` issue here :)

**Comment by dinosaure** [comment] 2021-03-23 10:26
As far as I can tell, the issue on `digestif` and `io-page` was fixed by
- `digestif.0.8.0`
- `io-page.2.4.0`

However, even if we are able to load `*.cmi` in `utop`, we still have a problem about variants where `utop` does not load the default implementation (see `digestif` and `checkseum`). However, the problem is more about `utop` than these libraries.

**Comment by samoht** [comment] 2022-01-07 22:22
I believe this is now fixed.

**Closed by samoht** 2022-01-07 22:22 UTC
Labels: type/bug
