### ISSUE TITLE
irmin-pack: make sure clear removes file on disk

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1334] opened 2021-03-25 08:15 UTC
Currently, `clear` just reset the file offsets without deleting the files. It would be nice if the files were deleted as well.

We need to be careful to signal such deletion to process which already have an open handle to the deleted files (for instance using a generation bump). That might need a file version upgrade for the pack file.

**Comment by icristescu** [comment] 2021-03-26 11:03
The issue is not in irmin-pack but in index. 

In irmin-pack, `clear` removes the files from disk (https://github.com/mirage/irmin/blob/master/src/irmin-pack/IO.ml#L164), and the new files only contain the header. so for instance this is an irmin-pack on disk after a clear:

```
icristes@Ioanas-MBP ~/D/i/_/l/upper1 (master)> ls -alh
drwxr-xr-x  7 icristes  staff   224B Mar 25 09:24 ./
drwxr-xr-x  7 icristes  staff   224B Mar 25 09:24 ../
drwxr-xr-x  6 icristes  staff   192B Mar 25 09:23 index/
-rw-r--r--  1 icristes  staff    24B Mar 25 09:23 store.branches
-rw-r--r--  1 icristes  staff    24B Mar 25 09:23 store.dict
-rw-r--r--  1 icristes  staff    24B Mar 25 09:23 store.pack
icristes@Ioanas-MBP ~/D/i/_/l/u/index (master)> ls -alh
drwxr-xr-x  6 icristes  staff   192B Mar 25 09:23 ./
drwxr-xr-x  7 icristes  staff   224B Mar 25 09:24 ../
-rw-r--r--  1 icristes  staff   205B Mar 25 09:23 data
-rw-------  1 icristes  staff     5B Mar 25 09:23 lock
-rw-r--r--  1 icristes  staff   197B Mar 25 09:23 log
-rw-r--r--  1 icristes  staff    65B Mar 25 09:23 log_async

```

I opened a draft to fix this in index https://github.com/mirage/index/pull/288.

**Comment by CraigFe** [comment] 2022-01-07 11:57
Closing as `clear` is no longer supported by `irmin-pack`.

**Closed by CraigFe** 2022-01-07 11:57 UTC
Labels: enhancement, users/tezos, disk usage
